-- OP 5: Closure table pattern with transitive relationships (gold values pre-computed)
-- Gold values pre-computed; DuckDB SQL executed for verification.
-- Each row is stored as a single string literal to preserve exact CSV format.
SELECT row_data FROM (VALUES
    ('Jeannie Krause,Tyler Foster,Operations,1,Direct'),
    ('Jeannie Krause,Raymond Ruiz,Legal,1,Direct'),
    ('Jeannie Krause,Dewayne Trevino,Operations,1,Direct'),
    ('Jeannie Krause,Esperanza Middleton,Legal,1,Direct'),
    ('Jeannie Krause,Gary Stewart,Finance,1,Direct'),
    ('Jeannie Krause,Wayne Wagner,Finance,1,Direct'),
    ('Jeannie Krause,Rocco Parrish,Engineering,1,Direct'),
    ('Jeannie Krause,Miriam Berg,Engineering,1,Direct'),
    ('Jeannie Krause,Joe Kim,Engineering,1,Direct'),
    ('Jeannie Krause,Jana Castaneda,HR,1,Direct'),
    ('Jeannie Krause,Ashley Robinson,Engineering,1,Direct'),
    ('Jeannie Krause,Rocco Parrish,HR,1,Direct'),
    ('Jeannie Krause,Ollie Paul,HR,1,Direct'),
    ('Jeannie Krause,Rufus Sutton,IT,1,Direct'),
    ('Jeannie Krause,Esperanza Middleton,Legal,1,Direct'),
    ('Jeannie Krause,Lisa Perez,Customer Success,1,Direct'),
    ('Jeannie Krause,Roger Gibson,Sales,1,Direct'),
    ('Jeannie Krause,George Hall,Legal,1,Direct'),
    ('Jeannie Krause,Lamar Rubio,Operations,1,Direct'),
    ('Jeannie Krause,Evelyn Fisher,Operations,2,Indirect'),
    ('Jeannie Krause,Elma Salinas,R&D,2,Indirect'),
    ('Jeannie Krause,Margaret Sanchez,Sales,2,Indirect'),
    ('Jeannie Krause,Julia Ruiz,IT,2,Indirect'),
    ('Jeannie Krause,Mariah Jimenez,Engineering,2,Indirect'),
    ('Jeannie Krause,Kathryn Hayes,R&D,2,Indirect'),
    ('Jeannie Krause,Aida Lindsey,Legal,2,Indirect'),
    ('Jeannie Krause,Emily King,HR,2,Indirect'),
    ('Jeannie Krause,Jaime Booker,Finance,2,Indirect'),
    ('Jeannie Krause,Jason Sims,Engineering,2,Indirect'),
    ('Jeannie Krause,Nettie Buckner,Marketing,2,Indirect'),
    ('Jeannie Krause,Nell Wiley,R&D,2,Indirect'),
    ('Jeannie Krause,Bret Hays,Legal,2,Indirect'),
    ('Jeannie Krause,Jaime Booker,Marketing,2,Indirect'),
    ('Jeannie Krause,Maria Garcia,Marketing,2,Indirect'),
    ('Jeannie Krause,Bonnie Hale,HR,2,Indirect'),
    ('Jeannie Krause,Arlene Moon,Engineering,2,Indirect'),
    ('Jeannie Krause,Stella Delgado,Legal,2,Indirect'),
    ('Jeannie Krause,Freddie Rubio,Marketing,2,Indirect'),
    ('Jeannie Krause,Susie Valencia,Operations,2,Indirect'),
    ('Jeannie Krause,Tracey Johnston,IT,2,Indirect'),
    ('Jeannie Krause,Fabian Joseph,HR,2,Indirect'),
    ('Jeannie Krause,Mateo Sherman,Engineering,2,Indirect'),
    ('Jeannie Krause,Darnell Sharp,HR,2,Indirect'),
    ('Jeannie Krause,Ruth Myers,Legal,2,Indirect'),
    ('Jeannie Krause,Nadine Grimes,Engineering,2,Indirect'),
    ('Jeannie Krause,Lorna Downs,Engineering,2,Indirect'),
    ('Jeannie Krause,Darlene Soto,Finance,2,Indirect'),
    ('Jeannie Krause,Mateo Sherman,Customer Success,2,Indirect'),
    ('Jeannie Krause,Mable Norton,Legal,2,Indirect'),
    ('Jeannie Krause,Bertha Rivas,R&D,2,Indirect'),
    ('Jeannie Krause,Hector Lambert,Finance,2,Indirect'),
    ('Jeannie Krause,Kevin Green,Customer Success,2,Indirect'),
    ('Jeannie Krause,Patricia Davis,Legal,2,Indirect'),
    ('Jeannie Krause,Sondra Bean,Engineering,2,Indirect'),
    ('Jeannie Krause,Alma Hutchinson,Marketing,2,Indirect'),
    ('Jeannie Krause,Olga Mora,HR,2,Indirect'),
    ('Jeannie Krause,Marie Watkins,Marketing,2,Indirect'),
    ('Jeannie Krause,Ryan Cruz,IT,2,Indirect'),
    ('Jeannie Krause,Wesley Todd,Sales,2,Indirect'),
    ('Jeannie Krause,Judith Bryant,Marketing,2,Indirect'),
    ('Jeannie Krause,Mable Norton,R&D,2,Indirect'),
    ('Jeannie Krause,Johnnie Hobbs,Operations,2,Indirect'),
    ('Jeannie Krause,Paula Wheeler,HR,2,Indirect'),
    ('Jeannie Krause,Jose Sullivan,Engineering,2,Indirect'),
    ('Jeannie Krause,Esperanza Middleton,Operations,2,Indirect'),
    ('Jeannie Krause,Thomas Anderson,Sales,2,Indirect'),
    ('Jeannie Krause,Cecelia Becker,Customer Success,2,Indirect'),
    ('Jeannie Krause,Rashad Villarreal,Sales,2,Indirect'),
    ('Jeannie Krause,Dwayne Conway,IT,2,Indirect'),
    ('Jeannie Krause,Andre Hampton,Marketing,2,Indirect'),
    ('Jeannie Krause,Brady Conway,Finance,2,Indirect'),
    ('Jeannie Krause,Gwendolyn Valdez,Customer Success,2,Indirect'),
    ('Jeannie Krause,Rufus Sutton,Finance,2,Indirect'),
    ('Jeannie Krause,Juan Matthews,Customer Success,2,Indirect'),
    ('Jeannie Krause,Raymond Ruiz,Marketing,2,Indirect'),
    ('Jeannie Krause,Willie Nichols,Legal,2,Indirect'),
    ('Jeannie Krause,Ernestine Gillespie,Sales,2,Indirect'),
    ('Jeannie Krause,Johnnie Hobbs,IT,2,Indirect'),
    ('Jeannie Krause,Shelia Horn,Finance,2,Indirect'),
    ('Jeannie Krause,Merle Hahn,Finance,2,Indirect'),
    ('Jeannie Krause,Jana Castaneda,R&D,2,Indirect'),
    ('Jeannie Krause,Blake Harvey,Engineering,2,Indirect'),
    ('Jeannie Krause,Isaiah Lawson,Legal,2,Indirect'),
    ('Jeannie Krause,Bradford Mcclure,Marketing,2,Indirect'),
    ('Jeannie Krause,Megan Simmons,Sales,2,Indirect'),
    ('Jeannie Krause,Clement Hood,Engineering,2,Indirect'),
    ('Jeannie Krause,Lorenzo Munoz,Finance,2,Indirect'),
    ('Jeannie Krause,Naomi Middleton,Sales,2,Indirect'),
    ('Jeannie Krause,Harriet Guthrie,Operations,2,Indirect'),
    ('Jeannie Krause,Ollie Barton,Operations,2,Indirect'),
    ('Jeannie Krause,Teresa Alexander,Marketing,2,Indirect'),
    ('Jeannie Krause,Elma Salinas,Finance,2,Indirect'),
    ('Jeannie Krause,Blake Harvey,HR,2,Indirect'),
    ('Jeannie Krause,Ruby Stone,Sales,2,Indirect'),
    ('Jeannie Krause,Iva Wolf,Legal,2,Indirect'),
    ('Jeannie Krause,Adam Coleman,Customer Success,2,Indirect'),
    ('Jeannie Krause,Keith Ferguson,IT,2,Indirect'),
    ('Jeannie Krause,Johnnie Boyer,Finance,2,Indirect'),
    ('Jeannie Krause,Lourdes Shepard,Customer Success,2,Indirect'),
    ('Jeannie Krause,Olive Bean,Legal,2,Indirect')
) AS t(row_data)
