//! DataMigrata CLI entry point.
//!
//! Usage:
//! ```bash
//! datamigrata translate < input.sql > output.sql
//! datamigrata translate --input mssql.sql --output duckdb.sql
//! datamigrata test50  # run the 50-operation test suite
//! ```

use std::io::{self, Read};
use std::path::PathBuf;
use clap::{Parser, Subcommand};
use datamigrata::{PipelineIntegration, PipelineResult};

#[derive(Parser, Debug)]
#[command(name = "datamigrata", version, about = "Energy-optimal MSSQL→DuckDB migration compiler")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Translate MSSQL T-SQL to DuckDB SQL.
    Translate {
        /// Input MSSQL T-SQL file (defaults to stdin).
        #[arg(long)]
        input: Option<PathBuf>,
        /// Output DuckDB SQL file (defaults to stdout).
        #[arg(long)]
        output: Option<PathBuf>,
    },
    /// Run the 50 SQL operations test suite.
    Test50,
    /// Generate DDL for a schema variant.
    Ddl {
        /// Schema variant: baseline, columnar, precomputed
        #[arg(long, default_value = "baseline")]
        variant: String,
    },
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
        .init();

    let cli = Cli::parse();

    match cli.command {
        Command::Translate { input, output } => {
            let tsql = match input {
                Some(path) => std::fs::read_to_string(path)?,
                None => {
                    let mut buf = String::new();
                    io::stdin().read_to_string(&mut buf)?;
                    buf
                }
            };

            let result = PipelineIntegration::new().run(&tsql)?;
            let duckdb_sql = format_output(&result);

            match output {
                Some(path) => std::fs::write(path, duckdb_sql)?,
                None => print!("{duckdb_sql}"),
            }
        }
        Command::Test50 => {
            eprintln!("Run via: cargo test --test operations_50");
        }
        Command::Ddl { variant } => {
            let v = match variant.as_str() {
                "baseline" => datamigrata::catalog::SchemaVariant::Baseline,
                "columnar" => datamigrata::catalog::SchemaVariant::ColumnarOptimized,
                "precomputed" => datamigrata::catalog::SchemaVariant::PreComputed,
                _ => anyhow::bail!("unknown variant: {}", variant),
            };
            let cat = datamigrata::catalog::Catalog::default_mssql_catalog(v);
            println!("{}", cat.ddl());
        }
    }

    Ok(())
}

fn format_output(result: &PipelineResult) -> String {
    let mut out = String::new();
    out.push_str("-- Generated by DataMigrata (MSSQL→DuckDB)\n");
    out.push_str(&format!("-- MSSQL constructs preprocessed: {}\n", result.preprocessed_constructs));
    out.push_str(&format!("-- Constructs lowered: {}\n", result.lowered_constructs));
    out.push_str(&format!("-- Optimization rules applied: {}\n", result.rules_applied));
    out.push('\n');
    out.push_str(&result.duckdb_sql);
    out.push('\n');
    out
}
