//! DataMigrata CLI entry point.
//!
//! Usage:
//! ```bash
//! datamigrata translate < input.sql > output.sql
//! datamigrata translate --input oracle.sql --output mssql.sql
//! datamigrata server --port 1521   # start TNS proxy server
//! ```

use std::io::{self, Read};
use std::path::PathBuf;
use clap::{Parser, Subcommand};
use datamigrata::{PipelineIntegration, PipelineResult};

#[derive(Parser, Debug)]
#[command(name = "datamigrata", version, about = "Oracle → MSSQL semantic translation middleware")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Translate an Oracle SQL script to MSSQL T-SQL.
    Translate {
        /// Input Oracle SQL file (defaults to stdin).
        #[arg(long)]
        input: Option<PathBuf>,
        /// Output T-SQL file (defaults to stdout).
        #[arg(long)]
        output: Option<PathBuf>,
    },
    /// Start the TNS proxy server (accepts Oracle client connections).
    Server {
        #[arg(long, default_value = "1521")]
        port: u16,
        /// MSSQL target host.
        #[arg(long, default_value = "localhost")]
        mssql_host: String,
        /// MSSQL target port.
        #[arg(long, default_value = "1433")]
        mssql_port: u16,
    },
    /// Run the 50 SQL operations test suite.
    Test50,
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
        .init();

    let cli = Cli::parse();

    match cli.command {
        Command::Translate { input, output } => {
            let oracle_sql = match input {
                Some(path) => std::fs::read_to_string(path)?,
                None => {
                    let mut buf = String::new();
                    io::stdin().read_to_string(&mut buf)?;
                    buf
                }
            };

            let result = PipelineIntegration::new().run(&oracle_sql)?;
            let tsql = format_tsql_output(&result);

            match output {
                Some(path) => std::fs::write(path, tsql)?,
                None => print!("{tsql}"),
            }
        }
        Command::Server { port, mssql_host, mssql_port } => {
            tracing::info!(%port, %mssql_host, %mssql_port, "starting TNS proxy server");
            // Stub: start the TNS server (src/protocol/tns/) that forwards
            // translated queries to MSSQL via the TDS client.
            eprintln!("TNS proxy server not yet implemented — see src/protocol/tns/");
        }
        Command::Test50 => {
            // Run the 50 SQL operations test harness.
            // The test suite lives in tests/operations_50.rs.
            eprintln!("Run via: cargo test --test operations_50");
        }
    }

    Ok(())
}

fn format_tsql_output(result: &PipelineResult) -> String {
    let mut out = String::new();
    out.push_str("-- Generated by DataMigrata\n");
    out.push_str(&format!("-- Oracle constructs preprocessed: {}\n", result.preprocessed_constructs));
    out.push_str(&format!("-- Constructs lowered: {}\n", result.lowered_constructs));
    out.push_str(&format!("-- Optimization rules applied: {}\n", result.rules_applied));
    out.push('\n');
    out.push_str(&result.tsql);
    out.push('\n');
    out
}
